extends Node
## Sound effect and music playback (`Sfx` autoload).
##
## Effects come from assets/audio/, generated by tools/gen_audio.py. WAV imports
## default to a non-looping stream, so the music stream's loop mode is set here.

const SFX_PATH := "res://assets/audio/%s.wav"
const VOICES := 8

var _streams: Dictionary = {}
var _voices: Array[AudioStreamPlayer] = []
var _next_voice := 0
var _music_player: AudioStreamPlayer
var _music_volume_db := -9.0


func _ready() -> void:
	for i in VOICES:
		var player := AudioStreamPlayer.new()
		player.bus = "Master"
		add_child(player)
		_voices.append(player)
	_music_player = AudioStreamPlayer.new()
	_music_player.bus = "Master"
	_music_player.volume_db = _music_volume_db
	add_child(_music_player)


func _load(name: String) -> AudioStream:
	if _streams.has(name):
		return _streams[name]
	var path := SFX_PATH % name
	var stream: AudioStream = null
	if ResourceLoader.exists(path):
		stream = load(path)
	else:
		push_warning("missing sound: %s" % path)
	_streams[name] = stream
	return stream


func play(name: String, pitch := 1.0, volume_db := 0.0) -> void:
	var stream := _load(name)
	if stream == null:
		return
	var player := _voices[_next_voice]
	_next_voice = (_next_voice + 1) % VOICES
	player.stream = stream
	player.pitch_scale = pitch
	player.volume_db = volume_db
	player.play()


## Play `name` only if it is not already sounding, so held inputs don't stack.
func play_once(name: String, pitch := 1.0) -> void:
	var stream := _load(name)
	if stream == null:
		return
	for player in _voices:
		if player.playing and player.stream == stream:
			return
	play(name, pitch)


func play_music(name := "music_zone") -> void:
	var stream := _load(name)
	if stream == null:
		return
	if stream is AudioStreamWAV:
		var wav := stream as AudioStreamWAV
		wav.loop_mode = AudioStreamWAV.LOOP_FORWARD
		wav.loop_begin = 0
		wav.loop_end = wav.data.size() / 2  # 16-bit mono: two bytes per frame
	_music_player.stream = stream
	_music_player.volume_db = _music_volume_db
	_music_player.play()


func stop_music() -> void:
	_music_player.stop()


func fade_music(duration := 0.6) -> void:
	if not _music_player.playing:
		return
	var tween := create_tween()
	tween.tween_property(_music_player, "volume_db", -60.0, duration)
	tween.tween_callback(_music_player.stop)
